### ISSUE TITLE
Lock dependency versions to prevent security issues

### ISSUE THREAD

**Issue by abose** [aicore/linode-object-storage-lib#5]
Merge in security update from https://github.com/aicore/template-nodejs
Changes to merge in: 
1. https://github.com/aicore/template-nodejs/pull/16 - Make sure that the `dependabot.yml` is in `.github` folder and not in `.github/workflows` . See bug fix pull request below.
2. https://github.com/aicore/template-nodejs/pull/17  - bug fix. 

## Details
Currently, our paclage.json files include dependencies of the format `"^16.0.2"` which pulls in the newest version. This can lead to vulnerabilities like this: https://fossbytes.com/developer-corrupts-faker-js-and-color-js/

## Fix:
1. Change dependencies to exact version locks like `"@commitlint/cli": "16.0.2",`
2. Enable dependabot automatic dependency upgrades and security checker in github.

**Comment by Ushmajit** [comment]
Fixed in the PR shown above. Verified dependabot is working (check for dependabot commits in the history). Closing this issue.
